In [1]:
from calc_core.Utils.CompositionLoader import CompositionExcelLoader
from calc_core.Composition.Composition import Composition
from calc_core.EOS.BaseEOS import EOSType

## Загрузка состава из БД

In [2]:
composition_db = Composition.from_db(r'C:\Users\sidor\OneDrive\Desktop\PVT\pvt_calc\PVTcalc\models.json')

In [3]:
comp_KRSNL = composition_db.KRSNL_PVTSIM

In [4]:
comp_KRSNL.normalize_composition()

In [5]:
comp_PRRZLM = composition_db.PRRZLM_MDT_TEST

## Старая загрузка составов

In [ ]:
xl_loader = CompositionExcelLoader(r'C:\Users\sidor\OneDrive\Desktop\PVT\compositions\xl\zap_mes.xlsx')
comp_dict = xl_loader.load(header=True, sheet = 'to_model')

In [ ]:
composition = Composition(comp_dict, eos_name= EOSType.PREOS)
composition.evaluate_composition_data({'critical_temperature': 'kesler lee',
                                                    'critical_pressure': 'kesler lee',
                                                    'acentric_factor': 'riazi al sahhaf',
                                                    'critical_volume': 'hall yarborough',
                                                    'Kw': 'k watson',
                                                    'shift_parameter': 'jhaveri youngren'})

composition.edit_component_properties('C36', 'molar_mass', 650)

In [ ]:
composition2 = Composition(comp_dict)
composition2.evaluate_composition_data({'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'riazi al sahhaf',
                                                    'critical_volume': 'hall yarborough',
                                                    'Kw': 'k watson',
                                                    'shift_parameter': 'jhaveri youngren'})

In [ ]:
composition2.normalize_composition()

In [ ]:
composition.composition_data.keys()

In [ ]:
for i in composition.composition_data['acentric_factor'].values():
    print(i)

## Расчет флеша

In [ ]:
from calc_core.VLE.Flash import Flash
from calc_core.Utils.Conditions import Conditions

In [ ]:
conds_stable = Conditions(250, 390)

In [ ]:
comp_KRSNL.T = conds_stable.t

In [ ]:
flash_obj1 = Flash(comp_KRSNL, conds_stable)

In [ ]:
flash_res1 = flash_obj1.calculate()

In [ ]:
flash_res1

In [ ]:
from calc_core.PhaseStability.PhaseIdentificator import PhaseIdentificator

In [ ]:
phase_iden = PhaseIdentificator(flash_obj1)

In [ ]:
phase_iden.identify_phase()

In [ ]:
from calc_core.Experiments.DLE import DLE

In [ ]:
dle_obj = DLE(comp_KRSNL, [330, 300, 270, 240, 210, 150, 100, 50, 30, 10, 5], 300, 110)

In [ ]:
dle_data = dle_obj.calculate()

In [ ]:
dle_data

In [ ]:
dle_obj._dle_df

In [ ]:
from calc_core.Experiments.SeparatorTest import SeparatorTest

In [ ]:
sep_test = SeparatorTest(comp_KRSNL, [210, 5.5, 1.6], [110, 25, 25], 300, 110)

In [ ]:
sep_test.calculate()

In [ ]:
sep_test._dle_df

## Работа через интерфейс  Model

In [7]:
from calc_core.CompositionalModel.CompositionalModel import CompositionalModel
from calc_core.Utils.Conditions import Conditions

In [8]:
model = CompositionalModel(comp_KRSNL)

In [ ]:
model.phase_envelope.ssm(t_min_c=200, t_max_c=400, p_min_bar=1, p_max_bar=1000, t_step_c=10)

In [ ]:
model.result_store_object._results

In [12]:
model.experiments.cce([350, 300, 270, 240, 210, 150, 100, 50, 30, 10, 5], 110)

Давление застряло на итерации 14. P=185.047483
Превышен лимит итераций (100). Последнее P=185.0475 bar

,pressure,temperature,is_two_phase,vapor_mole_frac,liquid_mole_frac,vapor_composition,liquid_composition,vapor_density,liquid_density,vapor_molar_density,...,liquid_molar_volume,vapor_molecular_ weight,liquid_molecular_ weight,vapor_viscosity,liquid_viscosity,vapor_z,liquid_z,v/v_res,v/v_sat,Compressibility
0,350.000000,383.14,False,0.000000,1.000000,"{'N2': 0.0032799672003279968, 'CO2': 0.0142298...","{'N2': 0.0032799672003279968, 'CO2': 0.0142298...",NaN,0.660655,NaN,...,137.295647,NaN,90.705065,NaN,0.272067,NaN,1.509268,1.000000,0.954084,0.000251
1,300.000000,383.14,False,0.000000,1.000000,"{'N2': 0.0032799672003279968, 'CO2': 0.0142298...","{'N2': 0.0032799672003279968, 'CO2': 0.0142298...",NaN,0.652477,NaN,...,139.016422,NaN,90.705065,NaN,0.250217,NaN,1.309872,1.012533,0.966041,0.000275
2,270.000000,383.14,False,0.000000,1.000000,"{'N2': 0.0032799672003279968, 'CO2': 0.0142298...","{'N2': 0.0032799672003279968, 'CO2': 0.0142298...",NaN,0.646930,NaN,...,140.208395,NaN,90.705065,NaN,0.236748,NaN,1.188993,1.021215,0.974325,0.000271
3,240.000000,383.14,False,0.000000,1.000000,"{'N2': 0.0032799672003279968, 'CO2': 0.0142298...","{'N2': 0.0032799672003279968, 'CO2': 0.0142298...",NaN,0.642024,NaN,...,141.279801,NaN,90.705065,NaN,0.225661,NaN,1.064959,1.029019,0.981770,0.000300
4,210.000000,383.14,False,0.000000,1.000000,"{'N2': 0.0032799672003279968, 'CO2': 0.0142298...","{'N2': 0.0032799672003279968, 'CO2': 0.0142298...",NaN,0.635505,NaN,...,142.729105,NaN,90.705065,NaN,0.212028,NaN,0.941398,1.039575,0.991841,0.000337
11,185.047483,383.14,False,0.000000,1.000000,"{'N2': 0.0032799672003279968, 'CO2': 0.0142298...","{'N2': 0.0032799672003279968, 'CO2': 0.0142298...",NaN,0.630320,NaN,...,143.903165,NaN,90.705065,NaN,0.202009,NaN,0.836363,1.048126,1.000000,0.001281
5,150.000000,383.14,True,0.147713,0.852287,"{'N2': 0.00841644900818925, 'CO2': 0.017647953...","{'N2': 0.002389742481690044, 'CO2': 0.01363745...",0.133894,0.651940,0.005697,...,156.996751,23.501356,102.352415,0.018608,0.236046,0.826922,0.739645,1.143494,1.090989,0.002861
6,100.000000,383.14,True,0.323362,0.676638,"{'N2': 0.00731605976440157, 'CO2': 0.019244290...","{'N2': 0.0013511423487291394, 'CO2': 0.0118334...",0.086437,0.681462,0.003692,...,180.293116,23.414276,122.862937,0.015582,0.293038,0.850789,0.566266,1.313174,1.252878,0.003656
7,50.000000,383.14,True,0.484647,0.515353,"{'N2': 0.006176564993639359, 'CO2': 0.02108265...","{'N2': 0.0005559599084725031, 'CO2': 0.0077853...",0.042708,0.713560,0.001744,...,214.387907,24.485914,152.978623,0.013670,0.370720,0.900356,0.336676,1.561505,1.489807,0.005305
8,30.000000,383.14,True,0.555451,0.444549,"{'N2': 0.005663629702334643, 'CO2': 0.02151431...","{'N2': 0.00030164963510173425, 'CO2': 0.005128...",0.026102,0.729122,0.001014,...,235.713440,25.750513,171.863905,0.013076,0.413491,0.929547,0.222099,1.716831,1.638000,0.006904
9,10.000000,383.14,True,0.650902,0.349098,"{'N2': 0.004992643624415806, 'CO2': 0.02090644...","{'N2': 8.663240475619139e-05, 'CO2': 0.0017811...",0.009467,0.750794,0.000324,...,273.595204,29.183536,205.413737,0.012362,0.476596,0.968234,0.085931,1.992745,1.901245,0.015813
10,5.000000,383.14,True,0.693250,0.306750,"{'N2': 0.0047133743314838866, 'CO2': 0.0201407...","{'N2': 4.049299122897237e-05, 'CO2': 0.0008713...",0.005089,0.760057,0.000160,...,294.523368,31.788902,223.854530,0.012031,0.505239,0.980986,0.046252,2.145176,2.046677,0.015299

In [14]:
model.experiments.dle([220, 180, 150, 130, 100, 50, 30, 10, 5], 300, 110)

,pressure,temperature,is_two_phase,vapor_mole_frac,liquid_mole_frac,vapor_composition,liquid_composition,vapor_density,liquid_density,vapor_molar_density,...,vapor_molar_volume,liquid_molar_volume,vapor_molecular_ weight,liquid_molecular_ weight,vapor_viscosity,liquid_viscosity,vapor_z,liquid_z,Bo,Rs
0,300.000000,383.14,False,0.000000,1.000000,"{'N2': 0.0032799672003279968, 'CO2': 0.0142298...","{'N2': 0.0032799672003279968, 'CO2': 0.0142298...",NaN,0.652477,NaN,...,NaN,139.016422,NaN,90.705065,NaN,0.250217,NaN,1.309872,1.485335,160.088130
1,185.041525,383.14,True,0.000024,0.999976,"{'N2': 0.009186896512218514, 'CO2': 0.01679531...","{'N2': 0.003279827123635907, 'CO2': 0.01422979...",0.169020,0.630973,0.007054,...,141.758225,143.756811,23.959928,90.706648,0.021531,0.203231,0.823870,0.835486,1.535948,160.088130
2,220.000000,383.14,False,0.000000,1.000000,"{'N2': 0.003279827123635907, 'CO2': 0.01422979...","{'N2': 0.003279827123635907, 'CO2': 0.01422979...",NaN,0.637768,NaN,...,NaN,142.225208,NaN,90.706648,NaN,0.216623,NaN,0.982745,1.519584,160.088130
3,180.000000,383.14,True,0.023073,0.976927,"{'N2': 0.00907605098626949, 'CO2': 0.016905912...","{'N2': 0.0031429299279409927, 'CO2': 0.0141665...",0.163886,0.634041,0.006864,...,145.688722,145.550560,23.876385,92.285068,0.021069,0.207677,0.823645,0.822864,1.519232,154.231909
4,150.000000,383.14,True,0.127619,0.872381,"{'N2': 0.008373393409016919, 'CO2': 0.01766962...","{'N2': 0.0023777725222833917, 'CO2': 0.0136541...",0.133920,0.651929,0.005698,...,175.507659,156.991031,23.504028,102.346953,0.018610,0.236029,0.826854,0.739618,1.429522,122.588397
5,130.000000,383.14,True,0.086080,0.913920,"{'N2': 0.007697353711291518, 'CO2': 0.01839328...","{'N2': 0.0018767309537412302, 'CO2': 0.0132077...",0.114682,0.663545,0.004901,...,204.037132,165.448938,23.399444,109.782874,0.017249,0.256839,0.833094,0.675536,1.376855,103.968453
6,100.000000,383.14,True,0.127655,0.872345,"{'N2': 0.006487796690665998, 'CO2': 0.01988517...","{'N2': 0.0012019714358211177, 'CO2': 0.0122306...",0.087038,0.680789,0.003700,...,270.245728,179.800099,23.521730,122.405883,0.015598,0.291516,0.848790,0.564718,1.305276,78.732584
7,50.000000,383.14,True,0.221070,0.778930,"{'N2': 0.0041166677716278815, 'CO2': 0.0240104...","{'N2': 0.0003747452058975739, 'CO2': 0.0088873...",0.044334,0.710502,0.001759,...,568.541105,211.107805,25.205566,149.992514,0.013650,0.362146,0.892839,0.331525,1.193756,40.608443
8,30.000000,383.14,True,0.106200,0.893800,"{'N2': 0.0024206133998162767, 'CO2': 0.0277269...","{'N2': 0.00013165918901270548, 'CO2': 0.006648...",0.028658,0.722867,0.001029,...,971.390274,227.575228,27.838274,164.506640,0.012952,0.394682,0.915285,0.214431,1.150209,26.342780
9,10.000000,383.14,True,0.156786,0.843214,"{'N2': 0.0007660218290021689, 'CO2': 0.0289617...","{'N2': 1.3706623348415037e-05, 'CO2': 0.002500...",0.012182,0.740003,0.000332,...,3015.794678,254.409727,36.737572,188.263854,0.011784,0.441410,0.947203,0.079905,1.084234,7.518552
10,5.000000,383.14,True,0.067832,0.932168,"{'N2': 0.0001800756291591759, 'CO2': 0.0229645...","{'N2': 1.6002874256306996e-06, 'CO2': 0.001010...",0.007555,0.746476,0.000164,...,6098.854504,266.064069,46.077056,198.610500,0.010972,0.458939,0.957767,0.041783,1.056987,0.651317
11,1.013250,293.14,True,0.006902,0.993098,"{'N2': 0.00018161184253860787, 'CO2': 0.030839...","{'N2': 3.4928220296542466e-07, 'CO2': 0.000803...",0.001550,0.788006,0.000042,...,23755.160900,253.468571,36.826176,199.734834,0.009174,0.754687,0.988094,0.010543,1.000000,0.000000

In [ ]:
conds = Conditions(100, 383)

In [ ]:
model.flash(110,99.85)

In [ ]:
model.flash(111, 99.85)

In [ ]:
model.result_store_object._results[0]

In [ ]:
model.result_store_object.get_by_module('Flash')

In [ ]:
from calc_core.Utils.Export import ModelJSONDB

In [ ]:
model_jsn = ModelJSONDB()

In [ ]:
model_jsn.export('PRRZLM_MDT_TEST', 'BASE', composition.composition, composition.composition_data,
                 composition.eos_name, None, field='PRRZLM')

In [ ]:
model_jsn.save()

## Новый переписанный модуль по расчету Psat

In [ ]:
from calc_core.PhaseEnvelope.new_methodv2 import SaturationPressure

In [ ]:
sat_p = SaturationPressure(composition, t_K= 110+273.15, p_max_bar=600)

In [ ]:
sat_p.sp_convergence_loop()

In [ ]:
sat_p.p_i

In [ ]:
import numpy as np

t_arr = np.linspace(273.15, 550+273.15, 20)

for t in t_arr:
    sat_p = SaturationPressure(composition=composition,
                               t_K=t, p_max_bar= 500)
    res_sp = sat_p.sp_convergence_loop()
    res_dp = sat_p.dp_convergence_loop()

    print('====')
    print(f'RESULT: PSAT:{res_sp}, PDEW:{res_dp}, T:{t-273.15}')
    print('====')

## Давление насыщения, давление конденсации и фазовая

In [ ]:
from calc_core.PhaseEnvelope.BubblePointPressure import BubblePointCalculator
from calc_core.PhaseEnvelope.DewPressure import DewPointCalculator
from calc_core.PhaseEnvelope.CriticalPoint import CriticalPointCalculator
from calc_core.PhaseEnvelope.PhaseEnvelopeGrid import PhaseEnvelopeGrid

### Psat

In [ ]:
p_sat_calc = BubblePointCalculator(comp_KRSNL, 110+273.15)
p_sat_calc.calculate()

### Pdew

In [ ]:
p_dew_calc = DewPointCalculator(comp_KRSNL, 330 + 273.15, P_guess= 260, dew_point_type = '')
p_dew_calc.calculate()

### EnvelopeFromStability

In [ ]:
comp_KRSNL.eos_name = EOSType.PREOS

In [ ]:
comp_KRSNL.normalize_composition()

In [ ]:
comp_PRRZLM.eos_name = EOSType.BRSEOS

In [ ]:
phase_env_from_stab = PhaseEnvelopeFromStability(composition, max_pressure=200, max_temperature=550, pressure_points=30, temperature_points=30)

In [ ]:
phase_env_from_stab.run_parallel()

In [ ]:
phase_env_from_stab.plot()

### Envelope SSM

In [ ]:
from calc_core.PhaseEnvelope.PhaseEnvelopeSuccessiveSubstitution import PhaseEnvelopeSSM

In [ ]:
phase_env_ssm = PhaseEnvelopeSSM(composition, p_max_bar=200, t_max_c=550, p_min_bar=0.1, t_min_c=10, t_step_c=25)

In [ ]:
envelope_df = phase_env_ssm.calculate_parallel()

In [ ]:
phase_env_ssm.plot()

### Envelope Newton

In [ ]:
from calc_core.PhaseEnvelope.PhaseEnvelopeNewton import PhaseEnvelopeNewton, SaturationPointNewton

In [ ]:
sat_point_newton = SaturationPointNewton(composition=comp_KRSNL, t_k= 280+273.15, p_max_bar= 300)

In [ ]:
sat_point_newton.find_bubble_point()

In [ ]:
phase_env_newton = PhaseEnvelopeNewton(composition=comp_KRSNL, p_max_bar=300, t_max_c=550, p_min_bar=0.1, t_min_c=10, t_step_c=5)

In [ ]:
phase_env_newton.calculate()

In [ ]:
phase_env_newton.plot()

### CritPoint

In [ ]:
crit_p = CriticalPointCalculator(comp_KRSNL)
crit_p.calculate()

# CCE в параллель - неэффективно

In [ ]:
from calc_core.Experiments.CCE import CCE

In [ ]:
cce = CCE(comp_KRSNL, [250, 200], 110)

In [ ]:
cce.calculate()

In [ ]:
cce.calculate_parallel()

In [ ]:
cce.calculate_parallel()